name: Release

on:
  workflow_dispatch:
  push:
    branches: [ master ]

permissions:
  contents: write
  pages: write
  id-token: write
  packages: write

concurrency:
  group: "release"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: gradle
          server-id: github
          settings-path: ${{ github.workspace }}
      - name: Check Git status
        id: git
        shell: bash
        run: |
          RESULT=$(git status)
          echo "::set-output name=status::$RESULT"
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: Publish package
        run: gradle clean publish reobfJar -Preckon.stage=final
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Fetch latest tag
        id: latesttag
        uses: WyriHaximus/github-action-get-previous-tag@v1
      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: build/libs/*.jar
          tag_name: ${{ steps.latesttag.outputs.tag }}
          generate_release_notes: true
      - name: Cleanup old packages
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'net.aerulion.voidworld'
          package-type: 'maven'
          min-versions-to-keep: 10
      - name: Cleanup old releases
        uses: dev-drprasad/delete-older-releases@v0.3.4
        with:
          keep_latest: 10
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup JavaDoc Pages
        uses: actions/configure-pages@v5
      - name: Upload JavaDoc
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/docs/javadoc/'
      - name: Deploy JavaDoc to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4